version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=mcatalan.42.fr
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
